version: '3'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=admin
      - DB_NAME=bayarind
      - DB_PORT=3306
    depends_on:
      - mysql

  mysql:
    image: mysql:8
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=bayarind
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:

networks:
  bayarind-network:
    driver: bridge